#+title: Documentation
* Keywords:
** =Packers=:

*** What:

Tools whose task consits of compressing executables and encrypting them simultaneosly.


*** Why there were created:

Bypass antivirus programs that analyse programs when they're loaded in memory, before they are executed.


*** How works:

During the execution the program passing throught a packer is load in memory, compresed and encrypted, then it will be decompressed and decrypted and finnally be executed.

**** Why they work that way.
Is related to the fact that =antivirus programs= generally *analyse programs when they are loaded in memory, before they are executed.* Throught =encryption= and =compresion= the packer could *bypass* by =obfuscating= the content of an executable until it execution.


*** Example:
       | type | Used to |
       | SFX  | Bundle a compressed payload and executable module into a single archive. |
       | =UPX= | Obfuscate the code by compressing and encrypting an executable.|

       UPX files can be modified after packing

There’s a known technique that hackers use with UPX to make analysis more difficult, and you need to be aware of it. Corrupted UPX files can’t be decompressed with standard versions of UPX, meaning you can’t view what’s inside. However, it doesn’t affect its ability to execute potentially malicious code inside, which means the payload remains armed.

How do hackers “break” the archive Then either:

    Pack the archive with an unreleased version of UPX.
    Or modify l_info and p_info structures in an archive.

These two actions have the same effect. Namely, the archive will not be openable by the standard version of UPX, which can hinder both you as a researcher if you want to unpack the contents and view them in a file browser, and a security system that won’t be able to reliably apply signature-based detection to an encrypted UPX file

* Goals:

** Mandatory:

*** Allowed functions:

- open, close, exit.
- fputsts, fflush, lseek.
- mmap, munmap, mprotect.
- perror, strerror.
- syscall.
- printf family.
- libft ones.

*** Requirements:

- Executable name: *woody_woodpacker*
- a binary parameter *ELF64 only*
- End of execution create a file =woody=.
- Free to choose encryption algorithm:
  *Complex is Important for grading score*
  - In case use encryption key, most randomly possible and display =stdout= when running the program
    How to check entropy [[https://foxptr.medium.com/understanding-packers-for-malware-ddc58caad229][entropy]]
- When running encrypted program should display -> =stdin= "....WOODY....\n" to indicated that the file is encrypted.
- The encrypt file isn't allowed to crash *if doesn't crash previously i supose*.
- It execution  after decryption must suffer no alteration.

** Bonus

*** DONE 32 bit Management.
CLOSED: [2025-11-07 Fri 16:57]

*** Parameterized key.
#+begin_quote
For Use the key in asm use the offset  inside your code.
#+end_quote
*** DONE Binary compression:
CLOSED: [2025-11-07 Fri 16:54]

*** Optimisation of the used algorithm throught asm.

*** Additional binay management (=PE=, =Mach-O=).


** Bibliography:
# How to make a packer
https://fasterthanli.me/series/making-our-own-executable-packer
# ELF format
https://gist.github.com/x0nu11byt3/bcb35c3de461e5fb66173071a2379779
# PE format
https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_dos_header
# MACH-O format
https://gpanders.com/blog/exploring-mach-o-part-1/
https://developer.apple.com/library/archive/documentation/Performance/Conceptual/CodeFootprint/Articles/MachOOverview.html#//apple_ref/doc/uid/20001860-BAJGJEJC

* How to Get the Source Code.
#+begin_quote
Type ~C-c C-c~ or mark the region and type ~M-x eval-region~
#+end_quote
#+begin_src emacs-lisp
  (require 'org)
  (require 'ob-tangle)

  (defun my/org-tangle-files (files)
    "Tangle RELATIVE-FILES based on the current buffer's directory."
    (dolist (file files)
      (message "Tangling %s..." file)
      (org-babel-tangle-file file)))

  (defun my/files-in-relative-dir (relative-dir filter)
    "Return a list of files in RELATIVE-DIR (relative to current buffer) matching FILTER.
  FILTER is a regex string and must be provided."
    (let* ((base-dir (file-name-directory (buffer-file-name)))
           (target-dir (expand-file-name relative-dir base-dir)))
      (directory-files target-dir t filter)))

  (my/org-tangle-files
   (my/files-in-relative-dir "./POC/" "\\.org$"))

#+end_src
* How to change the color of the promp for exit status last command
#+begin_src sh
  RED="\[\033[0;31m\]"
  GREEN="\[\033[0;32m\]"
  YELLOW="\[\033[0;33m\]"
  CYAN="\[\033[0;36m\]"
  RESET="\[\033[0m\]" # Reset color
  prompt_color() {
      if [[ $? -eq 0 ]]; then
  	echo -en "$GREEN" # Success color
      else
  	echo -en "$RED"   # Failure color
      fi
  }
  PS1="$(prompt_color)> ${RESET}"
#+end_src
* Auto assembly, patch, generate bytecod.
#+begin_src sh
  # xxd -h
      # -l len      stop after <len> octets.
      # -c cols     format <cols> octets per line. Default 16 (-i: 12, -ps: 30).
      # -ps         output in postscript plain hexdump style.
      # -r          reverse operation: convert (or patch) hexdump into binary.
      # -s [+][-]seek  start at <seek> bytes abs. (or +: rel.) infile offset.
  # ~str=$(echo -en "/proc/self/exe\x00" | hexdump -v -e '1/1 "%02x"')~
 gen_bin_stage()
  {
      nasm -f elf"$a" payload/elf/x"$a"/"$f".s
      off=$((0x$(readelf -WS payload/elf/x"$a"/"$f".o | grep .text | awk '{ print $6}')))
      len=$((0x$(readelf -WS payload/elf/x"$a"/"$f".o | grep .text | awk '{ print $7}')))
      if [[ "$f" == "stage1" ]]; then
  	xxd -s $off -l $len -p -c 0 payload/elf/x"$a"/"$f".o   | sed "s/\(c3\)\{15\}/$str/g" | xxd -r -p > bytecode/elf/x"$a"/"$f".bin
      else
  	echo "off -> 0x$off -> $((0x$off))"
  	echo "len -> 0x$len -> $((0x$len))"
  	dd if=payload/elf/x"$a"/"$f".o of=bytecode/elf/x"$a"/"$f".bin bs=1 skip=$(($off)) count=$(($len))
      fi
  }
#+end_src
* Auto Test
#+begin_src sh
  test_packer()
  {
    make
    ./woody_woodpacker ./dyn_link_x64
    if [[ $? -eq 0 ]]; then
        ./woody
    else
        echo "Error x64"
    fi
    ./woody_woodpacker ./dyn_link_x86
    if [[ $? -eq 0 ]]; then
        ./woody
    else
        echo "Error x86"
    fi
  }
#+end_src
