#+title: ELF
#+PROPERTY: header-args:c :tangle "srcs/elf/parser/inject_code.c :mkdirp yes" :mkdirp yes
* Validate ELF

** What makes invalid a elf file:
*** DONE Invalid Elf.
CLOSED: [2025-06-21 Sat 16:08]
:LOGBOOK:
- State "DONE"       from "TODO"       [2025-06-21 Sat 16:08]
CLOCK: [2025-06-21 Sat 15:31]--[2025-06-21 Sat 16:06] =>  0:35
CLOCK: [2025-06-21 Sat 13:21]--[2025-06-21 Sat 14:30] =>  1:09 
CLOCK: [2025-06-21 Sat 11:20]--[2025-06-21 Sat 12:25] =>  1:05
CLOCK: [2025-06-21 Sat 10:32]--[2025-06-21 Sat 10:59] =>  0:27
CLOCK: [2025-06-20 Fri 17:32]--[2025-06-20 Fri 19:46] =>  2:14
CLOCK: [2025-06-19 Thu 17:50]--[2025-06-19 Thu 18:38] =>  0:48
CLOCK: [2025-06-19 Thu 17:15]--[2025-06-19 Thu 17:38] =>  0:23
CLOCK: [2025-06-19 Thu 14:41]--[2025-06-19 Thu 15:03] =>  0:22
CLOCK: [2025-06-18 Wed 15:49]--[2025-06-18 Wed 15:51] =>  0:02
CLOCK: [2025-06-18 Wed 14:23]--[2025-06-18 Wed 15:14] =>  0:51
CLOCK: [2025-06-18 Wed 13:51]--[2025-06-18 Wed 14:06] =>  0:15
CLOCK: [2025-06-18 Wed 13:21]--[2025-06-18 Wed 13:36] =>  0:15
CLOCK: [2025-06-10 Tue 12:27]--[2025-06-10 Tue 13:29] =>  1:02
CLOCK: [2025-06-10 Tue 11:18]--[2025-06-10 Tue 11:49] =>  0:31
:END:
- Invalid Elf_header.
- Invalid Section_header.
- Invalid Program_header.

** Implementation
*** Abstraction

#+begin_comment
For simplify the 64/32 bits management we're going to use unions and getters for take the values from the unions and abstract the 64/32 for the code.
Abbreviation
Program header = Phdr = _ph       
Section header = Shdr = _sh       
Elf header = ehdr = _h       
#+end_comment

#+begin_src c :tangle include/format_elf.h 
#ifndef FORMAT_ELF_H
# define FORMAT_ELF_H
# include <elf.h>    // Typedef ELFNN_*, ST_BIND, ...
# include <stdint.h> // uint64_t
# include <stdbool.h> // bool
# include <unistd.h> // off_t
# include <string.h> // memcmp
# include "common.h" // overflows

   typedef union u_elf_h
   {
     Elf32_Ehdr	*elf32;
     Elf64_Ehdr	*elf64;
   }	t_elf_h;

   typedef union u_elf_ph
   {
     Elf32_Phdr	*elf32;
     Elf64_Phdr	*elf64;
   }	t_elf_ph;

   typedef union u_elf_sh
   {
     Elf32_Shdr	*elf32;
     Elf64_Shdr	*elf64;
   }	t_elf_sh;

   typedef union u_elf_sym
   {
     Elf32_Sym	*elf32;
     Elf64_Sym	*elf64;
   }	t_elf_sym;
#+end_src

*** Validation ELF_header
**** How works the header.
search man elf for the attributes of the structure:
=unsigned char e_ident[EI_NIDENT];= {Magicnbr, 32/64b, Dataencoding, version, OSABI, ABI, ...}
=uint16_t      e_type;= object file type {exec, rel, dyn, ...}
=uint16_t      e_machine;= required archictecture for a file *Ignored*
=uint32_t      e_version;= elf file version
=ElfN_Addr     e_entry;= entrypoint of the program (where is the first instruction to execute
=ElfN_Off      e_phoff;= Program header offset
=ElfN_Off      e_shoff;= Section header offset
=uint32_t      e_flags;= Processor-specific flags  *Ignored*
=uint16_t      e_ehsize;= elf header size Bytes
=uint16_t      e_phentsize;= elf program header size Bytes
=uint16_t      e_phnum;= nbr of program header
=uint16_t      e_shentsize;= elf section header size Bytes
=uint16_t      e_shnum;= nbr of section header
=uint16_t      e_shstrndx;= index of section header string (inside the array of section header)
***** Edge Cases
When the num of  =S/Phdr= is more than could be handle by uint16_t (65535) the first Sheader got the real info of =e_shnum, e_phnum, shstrndx=
*What value got then:*
- ===e_shnum == SHN_UNDEF===
  - ==e_shnum = shdr[0].sh_size== //Where to find
- ===e_phnum == PN_XNUM===
  - ==e_phnum = shdr[0].sh_info== //Where to find
- ===e_shstrndx == SHN_XINDEX===
  - ==e_shstrndx = shdr[0].sh_link== //Where to find
**** Coding
***** Creating the getters
I use the union attribute elf32 for e_ident case be a 64 is in the same place the first position (polymorphism).
#+begin_src c :tangle srcs/elf/parser/get_eh.c :mkdirp yes 
    #include "format_elf.h"

    uint16_t	elf_get_elfh_type(const t_elf_h *ehdr)
    {
      const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

      if (class == ELFCLASS32)
        return (ehdr->elf32->e_type);
      return (ehdr->elf64->e_type);
    }

    uint16_t	elf_get_elfh_machine(const t_elf_h *ehdr)
    {
      const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

      if (class == ELFCLASS32)
        return (ehdr->elf32->e_machine);
      return (ehdr->elf64->e_machine);
    }

    uint32_t	elf_get_elfh_version(const t_elf_h *ehdr)
    {
      const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

      if (class == ELFCLASS32)
        return (ehdr->elf32->e_version);
      return (ehdr->elf64->e_version);
    }

    uint32_t	elf_get_elfh_flags(const t_elf_h *ehdr)
    {
      const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

      if (class == ELFCLASS32)
        return (ehdr->elf32->e_flags);
      return (ehdr->elf64->e_flags);
    }

    uint16_t	elf_get_elfh_shstrndx(const t_elf_h *ehdr)
    {
      const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

      if (class == ELFCLASS32)
        return (ehdr->elf32->e_shstrndx);
      return (ehdr->elf64->e_shstrndx);
    }

#+end_src

#+begin_src c :tangle include/format_elf.h
  //get_eh
  uint16_t		elf_get_elfh_type(const t_elf_h *hdr);
  uint16_t		elf_get_elfh_machine(const t_elf_h *ehdr);// Unused
  uint32_t		elf_get_elfh_version(const t_elf_h *ehdr);// Unused
  uint32_t		elf_get_elfh_flags(const t_elf_h *ehdr); // Unused
  uint16_t		elf_get_elfh_shstrndx(const t_elf_h *ehdr);

#+end_src
***** TODO add prefix elf_funcname to each exclusive elf function.
#+begin_src c :tangle srcs/elf/parser/get_eh_1.c :mkdirp yes 
  #include "format_elf.h"

  uint16_t	elf_get_elfh_ehsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_ehsize);
    return (ehdr->elf64->e_ehsize);
  }

  uint16_t	elf_get_elfh_phentsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_phentsize);
    return (ehdr->elf64->e_phentsize);
  }

  uint16_t	elf_get_elfh_phnum(const t_elf_h *ehdr)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_phnum);
    return (ehdr->elf64->e_phnum);
  }

  uint16_t	elf_get_elfh_shentsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shentsize);
    return (ehdr->elf64->e_shentsize);
  }

  uint16_t	elf_get_elfh_shnum(const t_elf_h *ehdr)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shnum);
    return (ehdr->elf64->e_shnum);
  }
#+end_src

#+begin_src c :tangle include/format_elf.h
  //get_eh_1
  uint16_t		elf_get_elfh_ehsize(const t_elf_h *ehdr);
  uint16_t		elf_get_elfh_phentsize(const t_elf_h *ehdr);
  uint16_t		elf_get_elfh_phnum(const t_elf_h *ehdr);
  uint16_t		elf_get_elfh_shentsize(const t_elf_h *ehdr);
  uint16_t		elf_get_elfh_shnum(const t_elf_h *ehdr);
#+end_src

#+begin_src c :tangle srcs/elf/parser/get_eh_2.c :mkdirp yes 
  #include "format_elf.h"
  
uint64_t	elf_get_elfh_entry(const t_elf_h *ehdr)
{
	const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_entry);
	return (ehdr->elf64->e_entry);
}

uint64_t	elf_get_elfh_phoff(const t_elf_h *ehdr)
{
	const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_phoff);
	return (ehdr->elf64->e_phoff);
}

uint64_t	elf_get_elfh_shoff(const t_elf_h *ehdr)
{
	const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_shoff);
	return (ehdr->elf64->e_shoff);
}

int	elf_get_struct_size_elf_header(char *elf_mmap)
{
	if (elf_mmap[EI_CLASS] == ELFCLASS32)
		return (sizeof (Elf32_Ehdr));
	else if (elf_mmap[EI_CLASS] == ELFCLASS64)
		return (sizeof (Elf64_Ehdr));
	return (0);
}
#+end_src

#+begin_src c :tangle include/format_elf.h
  // get_eh_2
  uint64_t		elf_get_elfh_entry(const t_elf_h *ehdr);
  uint64_t		elf_get_elfh_phoff(const t_elf_h *ehdr);
  uint64_t		elf_get_elfh_shoff(const t_elf_h *ehdr);
  int				elf_get_struct_size_elf_header(char *elf_mmap);

#+end_src
***** Creating the getters for the edge cases

#+begin_src c :tangle srcs/elf/parser/get_real_data.c :mkdirp yes
  #include "format_elf.h"

  uint64_t	elf_get_real_phnum(const t_elf_h *ehdr)
  {
    const t_elf_sh	shdr = elf_get_section_header(ehdr, 0);
    uint64_t		phnum;

    phnum = elf_get_elfh_phnum(ehdr);
    if (PN_XNUM == phnum)
      phnum = elf_get_section_header_info(&shdr,
                                      elf_get_elfh_e_ident_class((void *)ehdr->elf32));
    return (phnum);
  }

  uint64_t	elf_get_real_shstrndx(const t_elf_h *ehdr, unsigned char class)
  {
    const t_elf_sh	shdr = elf_get_section_header(ehdr, 0);
    uint64_t		shstrndx;

    shstrndx = elf_get_elfh_shstrndx(ehdr);
    if (shstrndx == SHN_XINDEX)
      shstrndx = elf_get_section_header_link(&shdr, class);
    return (shstrndx);
  }

  uint64_t	elf_get_real_shnum(const t_elf_h *ehdr, unsigned char class)
  {
    const t_elf_sh	shdr = elf_get_section_header(ehdr, 0);
    uint64_t		shnum;

    shnum = elf_get_elfh_shnum(ehdr);
    if (shnum == SHN_UNDEF)
      shnum = elf_get_section_header_size(&shdr, class);
    return (shnum);
  }
#+end_src
****** Prototype of the functions
#+begin_src  c :tangle include/format_elf.h

  //get_real_data
  uint64_t	elf_get_real_shnum(const t_elf_h *ehdr, unsigned char class);
  uint64_t	elf_get_real_shstrndx(const t_elf_h *ehdr, unsigned char class);
  uint64_t	elf_get_real_phnum(const t_elf_h *ehdr);

#+end_src

***** Create the validation

****** Valid sh_off
Don't point out of the file. (The section header location is at the end of the file)
Don't point inside elf header struct (in case 0, a elf file must have section/s and should have an offset at least on executable files).
Don't got a number of entries that pass the filesize.
****** Valid ph_off
May don't exist in not executable programs.
Don't point out of the file. (The program header location is following the elf header)
Don't point inside elf header struct.
Don't got a number of entries that pass the filesize.

#+begin_src c :tangle srcs/elf/parser/valid_elf_h_attrib.c :mkdirp yes
  #include "format_elf.h"

  bool	elf_is_valid_elf_shoff(const t_elf_h *ehdr, off_t *elf_size)
  {
    const uint64_t shoff = elf_get_elfh_shoff(ehdr);
    const uint64_t elfhsize = (uint64_t)elf_get_struct_size_elf_header((char *)ehdr->elf32);
   const uint64_t shsize = elf_get_section_header_struct_size (ehdr);
   const uint64_t shnum = elf_get_elfh_shnum(ehdr);

    return (shoff < (uint64_t )*elf_size
            && shoff >= elfhsize  && 
            shoff + shnum * shsize < (uint64_t)*elf_size);
  }

  bool	elf_is_valid_elf_phoff(const t_elf_h *ehdr, off_t *elf_size)
  {
    return (!elf_get_elfh_phnum(ehdr)
            || (elf_get_elfh_phoff(ehdr) >= (uint64_t)elf_get_struct_size_elf_header((char *)ehdr->elf32)
            && elf_get_elfh_phoff(ehdr) < (uint64_t)elf_size
                && elf_get_elfh_phoff(ehdr) + elf_get_elfh_phnum(ehdr) * elf_get_elfh_phentsize(ehdr) < (uint64_t)elf_size));
  }
#+end_src

#+begin_src c :tangle include/format_elf.h
  // valid_elf_h_attrib
  
  bool	elf_is_valid_elf_shoff(const t_elf_h *ehdr, off_t *elf_size);
  bool	elf_is_valid_elf_phoff(const t_elf_h *ehdr, off_t *elf_size);

#+end_src
******  An executable must be a exec or dyn and got PH and entrypoint.
#+begin_src c :tangle srcs/elf/parser/validate_elf_h.c :mkdirp yes
  #include "format_elf.h"

  bool elf_is_file_size_enought_for_elf_header(off_t file_size, void *elf_mmap)
  {
    if (file_size < EI_NIDENT)
      return (false);
    return (file_size
            >= elf_get_struct_size_elf_header(elf_mmap));
  }

  bool	elf_is_valid_elf_data_format(char *elf_mmap)
  {
    const char	data = elf_mmap[EI_DATA];

    return (ELFDATA2LSB == data|| ELFDATA2MSB == data);
  }

  bool	elf_is_valid_elf_version(char *elf_mmap)
  {
    return (EV_CURRENT == elf_mmap[EI_VERSION]);
  }

  bool	elf_is_executable_elf_file(void *elf_mmap)
  {
    const t_elf_h ehdr = (t_elf_h){.elf32 = elf_mmap};
    const uint16_t type = elf_get_elfh_type(&ehdr);

    return ((ET_EXEC == type || ET_DYN == type) && elf_get_elfh_phnum(&ehdr) && elf_get_elfh_entry(&ehdr));
  }
#+end_src

#+begin_src c :tangle include/format_elf.h
  // validate_elf_h
  bool	elf_is_file_size_enought_for_elf_header(off_t file_size, void *elf_mmap);
  bool	elf_is_valid_elf_data_format(char *elf_mmap);
  bool	elf_is_valid_elf_version(char *elf_mmap);
  bool	elf_is_executable_elf_file(void *elf_mmap);

#+end_src
****** Check integrity in section size, not shstrndx upper shnum, a wrapper of the e_ident validation
#+begin_src c :tangle srcs/elf/parser/validate_elf_h_1.c :mkdirp yes 
  #include "format_elf.h"

  bool	elf_valid_section_size(const t_elf_h *ehdr)
  {
    return (elf_get_elfh_shentsize(ehdr) == elf_get_section_header_struct_size(ehdr));
  }

  bool	elf_valid_section_header_string_index(const t_elf_h *ehdr)
  {
    const uint16_t	shnum = elf_get_elfh_shnum(ehdr);

    return (shnum && shnum > elf_get_elfh_shstrndx(ehdr));
  }

  bool	elf_valid_elfh_class(const char *e_indent)
  {
    const unsigned char	class = elf_get_elfh_e_ident_class((void *)e_indent);

    return (class == ELFCLASS64 || class == ELFCLASS32);
  }

  bool	elf_valid_ident(off_t file_size, void *elf_mmap)
  {
    return (elf_is_file_size_enought_for_elf_header(file_size, elf_mmap)
            && elf_valid_elf_magic_number(elf_mmap)
            && elf_valid_elfh_class(elf_mmap) && elf_is_valid_elf_data_format(elf_mmap)
            && elf_is_valid_elf_version(elf_mmap));
  }

#+end_src

#+begin_src c :tangle include/format_elf.h
  // valid_elf_h_1
  bool	elf_valid_section_size(const t_elf_h *ehdr);
  bool	elf_valid_ident(off_t file_size, void *elf_mmap);
  bool	elf_valid_elfh_class(const char *e_indent);
  bool	elf_valid_section_header_string_index(const t_elf_h *ehdr);

#+end_src
****** Wrapper validation rest elfheader attributes, wrapper of wrappers.
#+begin_src c :tangle srcs/elf/parser/valid_elf_h_2.c :mkdirp yes
  #include "format_elf.h"

  bool	elf_valid_t_elf_h(const t_elf_h *ehdr, off_t file_size)
  {
    return (elf_valid_section_size(ehdr)
            && elf_valid_section_header_string_index(ehdr)
            && elf_is_valid_elf_shoff(ehdr, &file_size)
            && elf_is_valid_elf_phoff(ehdr, &file_size));
  }

  bool	elf_valid_elf_header(const t_elf_h *ehdr, off_t file_size)
  {
    return (elf_valid_ident(file_size, (void *)ehdr->elf32) && elf_valid_t_elf_h(ehdr, file_size));
  }
#+end_src

#+begin_src c :tangle include/format_elf.h
  // elf_valid_t_elf_h_2
  bool	elf_valid_elf_header(const t_elf_h *ehdr, off_t file_size);
  bool	elf_valid_t_elf_h(const t_elf_h *ehdr, off_t file_size);

#+end_src

*** DONE Validation ELF_Programs.
CLOSED: [2025-06-19 Thu 17:46]

:LOGBOOK:
- State "DONE"       from "TODO"       [2025-06-19 Thu 17:46]
:END:
*** Check integrite struct size with elfheader, phnum not 0 cause this only work on executable, check alignment, check the content of a header + offset exceed file size
#+begin_src c :tangle  srcs/elf/parser/valid_program_header.c :mkdirp yes 
  #include "format_elf.h"

    static bool	elf_valid_elf_ph(unsigned char elf_class, off_t elf_size, const t_elf_h *ehdr,
                            uint16_t index)
    {
            const t_elf_ph	phdr = elf_get_program_header(ehdr, index);
            const uint16_t	size = elf_get_struct_size_elf_ph(elf_class);
            unsigned char	p_align;

            if (!phdr.elf32 || !ehdr->elf32
                    || (void *)phdr.elf32 + size >= (void *)ehdr->elf32 + elf_size)
                    return (false);
            p_align = elf_get_program_header_align(&phdr, elf_class);
            if (p_align != (p_align & -p_align))
                    return (false);
            if ((off_t)(elf_get_program_header_offset(&phdr, elf_class)
                    + elf_get_program_header_filesz(&phdr, elf_class)) >= elf_size)
                    return (false);
            return (true);
    }

    bool	elf_valid_elf_phs(off_t elf_size, const t_elf_h *ehdr)
    {
            const uint64_t		real_phnum	= elf_get_real_phnum(ehdr);
            const unsigned char	class		= elf_get_elfh_e_ident_class((void *)ehdr->elf32);
            uint64_t			index;

            if (!real_phnum)
                    return (true);
            if (elf_get_struct_size_elf_ph(class) != elf_get_elfh_phentsize(ehdr))
                    return (false);
            if (signed_overflow_limit (real_phnum, elf_get_struct_size_elf_ph(class), elf_size))
                    return (false);
            index = 0;
            while (index < real_phnum
                    && elf_valid_elf_ph(class, elf_size, ehdr, index))
                    index++;
            return (index >= real_phnum);
    }
#+end_src

#+begin_src c :tangle include/format_elf.h
  // elf_valid_elf_ph
  bool	elf_valid_elf_phs(off_t elf_size, const t_elf_h *ehdr);
#+end_src


#+begin_src c :tangle  srcs/elf/parser/valid_program_header_2.c :mkdirp yes 
   #include "format_elf.h"

   uint64_t	elf_get_struct_size_elf_ph(unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (sizeof(Elf32_Phdr));
           return (sizeof(Elf64_Phdr));
   }

   t_elf_ph	elf_get_program_header(const t_elf_h *ehdr, uint16_t index)
   {
           const uint64_t	offset = elf_get_elfh_phoff(ehdr);
           const uint64_t	size = elf_get_struct_size_elf_ph(
                           elf_get_elfh_e_ident_class((void *)ehdr->elf32));

           if (unsigned_int_mult_overflow(size, index, sizeof(size) * 8))
                   return ((t_elf_ph){.elf32 = NULL});
           return ((t_elf_ph){.elf32 = (void *)ehdr->elf32 + offset
                   + size * index});
   }

   uint64_t elf_get_program_header_align(const t_elf_ph *phdr,
                           unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (phdr->elf32->p_align);
           return (phdr->elf64->p_align);
   }

   uint32_t	elf_get_program_header_offset(const t_elf_ph *phdr,
                           unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (phdr->elf32->p_offset);
           return (phdr->elf64->p_offset);
   }

   uint64_t	elf_get_program_header_filesz(const t_elf_ph *phdr,
                           unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (phdr->elf32->p_filesz);
           return (phdr->elf64->p_filesz);
   }

   uint64_t	elf_get_program_header_memsz(const t_elf_ph *phdr,
                           unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (phdr->elf32->p_memsz);
           return (phdr->elf64->p_memsz);
   }

     uint64_t	elf_get_program_header_vaddr(const t_elf_ph *phdr,
                             unsigned char class)
     {
             if (class == ELFCLASS32)
                     return (phdr->elf32->p_vaddr);
             return (phdr->elf64->p_vaddr);
     }

     uint64_t	elf_get_program_header_paddr(const t_elf_ph *phdr,
                             unsigned char class)
     {
             if (class == ELFCLASS32)
                     return (phdr->elf32->p_paddr);
             return (phdr->elf64->p_paddr);
     }

  uint64_t elf_get_program_header_type(t_elf_ph *phdr, unsigned char class)
  {
    if (class == ELFCLASS32) 
        return (phdr->elf32->p_type);
    return (phdr->elf64->p_type);
  }


#+end_src

#+begin_src c :tangle include/format_elf.h

  // valid_program_header_2
    uint64_t	elf_get_struct_size_elf_ph(unsigned char class);
    t_elf_ph	elf_get_program_header(const t_elf_h *ehdr, uint16_t index);
    uint32_t	elf_get_program_header_offset(const t_elf_ph *phdr,
                            unsigned char class);
    uint64_t	elf_get_program_header_filesz(const t_elf_ph *phdr,
                            unsigned char class);
  uint64_t	elf_get_program_header_memsz(const t_elf_ph *phdr,
  					      unsigned char class);
  uint64_t elf_get_program_header_align(const t_elf_ph *phdr,
                            unsigned char class);

  uint64_t	elf_get_program_header_vaddr(const t_elf_ph *phdr,
                          unsigned char class);
  uint64_t	elf_get_program_header_paddr(const t_elf_ph *phdr,
                          unsigned char class);
  uint64_t elf_get_program_header_type(t_elf_ph *phdr, unsigned char class);
#+end_src

***** DONE Check that compile and work succesfully
CLOSED: [2025-06-24 Tue 19:26]
:LOGBOOK:
- State "DONE"       from "TODO"       [2025-06-24 Tue 19:26]
:END:

***** DONE Fix errors.
CLOSED: [2025-06-25 Wed 13:07]
:LOGBOOK:
- State "DONE"       from "TODO"       [2025-06-25 Wed 13:07]
:END:
#+begin_src  c :tangle srcs/elf/parser/get_elfh_e_ident.c :mkdirp yes
#include "format_elf.h"

  unsigned char	elf_get_elfh_e_ident_class(const unsigned char *e_ident)
  {
          return (e_ident[EI_CLASS]);
  }

  unsigned char	elf_get_elfh_e_ident_data(const unsigned char *e_ident)
  {
          return (e_ident[EI_DATA]);
  }

  unsigned char	elf_get_elfh_e_ident_version(const unsigned char *e_ident)
  {
          return (e_ident[EI_VERSION]);
  }

  unsigned char	elf_get_elfh_e_ident_osabi(const unsigned char *e_ident)
  {
          return (e_ident[EI_OSABI]);
  }

  unsigned char	elf_get_elfh_e_ident_abiversion(const unsigned char *e_ident)
  {
          return (e_ident[EI_ABIVERSION]);
  }
#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes

// elf_get_elfh_e_ident
  unsigned char	elf_get_elfh_e_ident_data(const unsigned char *e_ident);
  unsigned char	elf_get_elfh_e_ident_class(const unsigned char *e_ident);
  unsigned char	elf_get_elfh_e_ident_version(const unsigned char *e_ident);
  unsigned char	elf_get_elfh_e_ident_osabi(const unsigned char *e_ident);
  unsigned char	elf_get_elfh_e_ident_abiversion(const unsigned char *e_ident);
#+end_src

*****  Wrapper of wrapper of wrappers xD
#+begin_src c :tangle srcs/elf/parser/valid_elfh.c :mkdirp yes
  #include "format_elf.h"

  bool	elf_valid_elf_magic_number(void *elf_mmap)
  {
          return (!memcmp(elf_mmap, ELFMAG, (size_t)SELFMAG));
  }

  bool elf_valid_elf_file(void *elf_mmap, off_t elf_size)
  {
    const t_elf_h ehdr = (t_elf_h){.elf32 = elf_mmap};
    const unsigned char class = elf_get_elfh_e_ident_class(elf_mmap);

    if (elf_valid_elf_header(&ehdr, elf_size)
        && elf_valid_elf_section_headers(class, &ehdr)
        && elf_valid_elf_phs(elf_size, &ehdr))
        return (true);
    return (false);
  }

#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes
    // elf_valid_elfh

  bool	elf_valid_elf_magic_number(void *elf_mmap);
  bool	elf_valid_elf_file(void *elf_mmap, off_t elf_size);

#+end_src

*** DONE Validation ELF_Sections.
CLOSED: [2025-06-25 Wed 12:54]
:LOGBOOK:
- State "DONE"       from "TODO"       [2025-06-25 Wed 12:54]
:END:
change =t_bag=  struct to =size= and =class= add things as needed.

**** DONE Getters Section Headers
CLOSED: [2025-06-18 Wed 15:51]
:LOGBOOK:
- State "DONE"       from              [2025-06-18 Wed 15:51]
:END:

**** Check for special section index, null char at the end of the section strtab.
#+begin_src c :tangle  srcs/elf/parser/get_elfsh_data.c :mkdirp yes
    #include "format_elf.h"

    uint64_t	elf_get_section_header_struct_size(const t_elf_h *ehdr)
    {
            const unsigned char	class = elf_get_elfh_e_ident_class(ehdr->elf32->e_ident);

            if (class == ELFCLASS32)
                    return (sizeof (Elf32_Shdr));
            return (sizeof (Elf64_Shdr));
    }

  bool	elf_is_special_section_index(uint16_t index)
  {
    static const uint16_t	special_section_index[] = {SHN_COMMON, SHN_ABS,
                                                     SHN_XINDEX};
    uint16_t						i;

    if (SHN_LOPROC <= index && index >= SHN_HIOS)
      return (true);
    i = 0;
    while (i < (sizeof (special_section_index) / sizeof (*special_section_index))  && index != special_section_index[i])
      i++;
    return (i != (sizeof (special_section_index) / sizeof (*special_section_index)));
  }

    t_elf_sh	elf_get_section_header(const t_elf_h *ehdr, uint16_t index)
    {
            const uint64_t			sh_offset = elf_get_elfh_shoff(ehdr);
            const uint64_t			sh_size = elf_get_section_header_struct_size(ehdr);
            const void				*base = (void*)ehdr->elf32;
            t_elf_sh				shdr;

            if (!sh_offset || index >= elf_get_elfh_shnum(ehdr)
                    || elf_is_special_section_index(index))
            {
                    shdr.elf32 = NULL;
                    return (shdr);
            }
            shdr.elf64 = (void *) (base) + sh_offset + index * sh_size;
            return (shdr);
    }

    uint64_t	elf_get_section_header_offset(const t_elf_sh *shdr, unsigned char class)
    {
            if (!shdr->elf32)
            {
  //                  ft_printf("section header Invalid\n");
                    return (0);
            }
            if (class == ELFCLASS32)
                    return ((uint64_t)shdr->elf32->sh_offset);
            return (shdr->elf64->sh_offset);
    }

    bool	valid_null_end_string_table(const t_elf_sh *shstrtab,
                            unsigned char class, char *ptr)
    {
            const uint64_t	size = elf_get_section_header_size(shstrtab, class);

            if (!ptr || !size)
                    return (false);
            return (!ptr[size - 1]);
    }

#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes
  // get_elfsh_data
  uint64_t	elf_get_section_header_struct_size(const t_elf_h *ehdr);
  bool	elf_is_special_section_index(uint16_t index);
  t_elf_sh	elf_get_section_header(const t_elf_h *ehdr, uint16_t index);
  uint64_t	elf_get_section_header_offset(const t_elf_sh *shdr, unsigned char class);
  bool	valid_null_end_string_table(const t_elf_sh *shstrtab,
                                      unsigned char class, char *ptr);

#+end_src

#+begin_src c :tangle srcs/elf/parser/get_elfsh_data_1.c :mkdirp yes 
  #include "format_elf.h"

   uint32_t	elf_get_section_header_type(const t_elf_sh *shdr, unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (shdr->elf32->sh_type);
           return (shdr->elf64->sh_type);
   }

   uint32_t	elf_get_section_header_flags(const t_elf_sh *shdr, unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (shdr->elf32->sh_flags);
           return (shdr->elf64->sh_flags);
   }

   uint64_t	elf_get_section_header_size(const t_elf_sh *shdr, unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (shdr->elf32->sh_size);
           return (shdr->elf64->sh_size);
   }

   uint32_t	elf_get_section_header_link(const t_elf_sh *shdr, unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (shdr->elf32->sh_link);
           return (shdr->elf64->sh_link);
   }

   uint32_t	elf_get_section_header_info(const t_elf_sh *shdr, unsigned char class)
   {
           if (class == ELFCLASS32)
                   return (shdr->elf32->sh_info);
           return (shdr->elf64->sh_info);
   }
#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes
  // get_elfsh_data_1
uint32_t	elf_get_section_header_type(const t_elf_sh *shdr, unsigned char class);
uint32_t	elf_get_section_header_flags(const t_elf_sh *shdr, unsigned char class);
uint64_t	elf_get_section_header_size(const t_elf_sh *shdr, unsigned char class);
uint32_t	elf_get_section_header_link(const t_elf_sh *shdr, unsigned char class);
uint32_t	elf_get_section_header_info(const t_elf_sh *shdr, unsigned char class);
#+end_src

#+begin_src c :tangle srcs/elf/parser/get_elfsh_data_2.c :mkdirp yes 
#include "format_elf.h"

uint64_t	elf_get_section_header_addralign(const t_elf_sh *shdr,
		unsigned char class)
{
	if (class == ELFCLASS32)
		return ((uint64_t)shdr->elf32->sh_addralign);
	return (shdr->elf64->sh_addralign);
}

uint32_t	elf_get_section_header_entsize(const t_elf_sh *shdr,
			unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_entsize);
	return (shdr->elf64->sh_entsize);
}

uint32_t	elf_get_section_header_addr(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_addr);
	return (shdr->elf64->sh_addr);
}
#+end_src
#+begin_src c :tangle include/format_elf.h :mkdirp yes
  // get_elfsh_data_2

  uint64_t	elf_get_section_header_addralign(const t_elf_sh *shdr,
                      unsigned char class);
  uint32_t	elf_get_section_header_entsize(const t_elf_sh *shdr,
                      unsigned char class);
  uint32_t	elf_get_section_header_addr(const t_elf_sh *shdr, 
                      unsigned char class);

#+end_src

#+begin_src c :tangle srcs/elf/parser/get_elfsh_data_3.c :mkdirp yes 
  #include "format_elf.h"

    const char	*elf_get_section_string_table(const t_elf_h *ehdr)
    {
            const uint16_t	sh_str_index = elf_get_elfh_shstrndx(ehdr);
            const t_elf_sh	shstrtab_shdr = elf_get_section_header(ehdr, sh_str_index);
            const uint64_t	shstr_tab_offset = elf_get_section_header_offset(&shstrtab_shdr,
                            elf_get_elfh_e_ident_class(ehdr->elf32->e_ident));
            char			*ptr;

            if (!shstr_tab_offset && !shstrtab_shdr.elf32)
                    return (NULL);
            ptr = (char *)ehdr->elf32 + shstr_tab_offset;
            if (!valid_null_end_string_table(&shstrtab_shdr,
                            elf_get_elfh_e_ident_class((void *)ehdr->elf32), ptr))
                    return (NULL);
            return (ptr);
    }

    uint32_t	elf_get_section_header_name(const t_elf_sh *shdr, unsigned char class)
    {
            if (!shdr || !shdr->elf32)
                    return (0);
            if (class == ELFCLASS32)
                    return (shdr->elf32->sh_name);
            if (class == ELFCLASS64)
                    return (shdr->elf64->sh_name);
            return (0);
    }

    const char	*elf_get_section_name(const char *str_tab, uint64_t index_str_tab)
    {
            if (!str_tab)
                    return (NULL);
            return (str_tab + index_str_tab);
    }
#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes
  // get_elfsh_data_3

  const char	*elf_get_section_string_table(const t_elf_h *ehdr);
  uint32_t	elf_get_section_header_name(const t_elf_sh *shdr, unsigned char class);
  const char	*elf_get_section_name(const char *str_tab, uint64_t index_str_tab);
#+end_src

**** DONE Validation Functions
CLOSED: [2025-06-20 Fri 19:31]
:LOGBOOK:
- State "DONE"       from "REVIEW"     [2025-06-20 Fri 19:31]
:END:

**** elf valid section header got a var for true or false and another for save the index.
#+begin_src c :tangle srcs/elf/parser/valid_section_header.c :mkdirp yes
  #include "format_elf.h"

    bool	elf_valid_elf_section_header_symtab_shndx(unsigned char class, const uint64_t symtab_index, const t_elf_h *ehdr)
    {
            const t_elf_sh	shdr = elf_get_section_header_by_type(ehdr, SHT_SYMTAB_SHNDX);

            if (!shdr.elf32)
                    return (false);
            return (elf_get_section_header_link(&shdr, class) == symtab_index);
    }

    bool	elf_valid_elf_section_headers(unsigned char elf_class, const t_elf_h *ehdr)
    {
            const uint64_t	eh_shnum = elf_get_real_shnum(ehdr, elf_class);
            const uint64_t	real_shstrndx = elf_get_real_shstrndx(ehdr, elf_class);
            uint64_t		id;
            uint64_t		symtab_shndx[2];

            if (!eh_shnum || !real_shstrndx)
                    return (false);
            id = 0;
            bzero(symtab_shndx, sizeof (symtab_shndx));
            while (id < eh_shnum && elf_valid_elf_section_header_handler(elf_class, &symtab_shndx[0], ehdr, id))
                    id++;
            if (id < eh_shnum)
                    return (false);
            if (real_shstrndx >= eh_shnum
                    || elf_get_section_header_type_by_index(ehdr, real_shstrndx)
                    != SHT_STRTAB)
                    return (false);
            return (!symtab_shndx[0]
                    || elf_valid_elf_section_header_symtab_shndx(elf_class, symtab_shndx[1], ehdr));
    }
#+end_src


#+begin_src c :tangle include/format_elf.h :mkdirp yes
  // elf_valid_elf_section_header
  bool	elf_valid_elf_section_header_symtab_shndx(unsigned char class, const uint64_t symtab_index, const t_elf_h *ehdr);
  bool	elf_valid_elf_section_headers(unsigned char elf_class, const t_elf_h *ehdr);

#+end_src

****  wrapper case when link point to another section index for more info mustn't link with itself, and setter for symtab_ndx, check integrity that in case the first sh got the value of current sh, ph, strndx got a not zero value, check type overflow.
#+begin_src c :tangle srcs/elf/parser/valid_elf_section_header_2.c :mkdirp yes 
  #include "format_elf.h"

  bool	elf_valid_section_header(unsigned char elf_class, const t_elf_sh *shdr, uint16_t index, const t_elf_h *ehdr, uint64_t *symtab)
  {
          const uint32_t	type = elf_get_section_header_type(shdr, elf_class);
          const uint32_t	link = elf_get_section_header_link(shdr, elf_class);
          const uint64_t	real_shnum = elf_get_real_shnum(ehdr, elf_class);

          if (real_shnum <= link)
                  return (false);
          if ((elf_get_section_header_flags(shdr, elf_class) & SHF_INFO_LINK
                          || type == SHT_RELA || type == SHT_REL)
                  && (elf_get_section_header_info(shdr, elf_class) >= real_shnum
                          || elf_get_section_header_info(shdr, elf_class) == index))
                  return (false);
          if (link == index)
                  return (false);
          if (type == SHT_SYMTAB_SHNDX)
                  symtab[0] = true;
          else if (type == SHT_SYMTAB)
                  symtab[1] = index;
          return (true);
  }

  bool	elf_valid_first_section_header(unsigned char elf_class, const t_elf_h *ehdr,
                          const t_elf_sh *shdr)
  {
          if (elf_get_elfh_shnum(ehdr) == SHN_UNDEF && !elf_get_section_header_size(shdr, elf_class))
            return (false);
          if (elf_get_elfh_shstrndx(ehdr) == SHN_XINDEX && !elf_get_section_header_link(shdr, elf_class))
            return (false);
          if (elf_get_elfh_phnum(ehdr) == PN_XNUM &&!elf_get_section_header_info(shdr, elf_class))
            return (false);
          return (!uint_mult_overflow(elf_get_real_shnum(ehdr, elf_class),
                          elf_get_section_header_struct_size(ehdr)));
  }

  uint32_t	elf_get_section_header_type_by_index(const t_elf_h *ehdr,
                          uint16_t index)
  {
          const unsigned char	class = elf_get_elfh_e_ident_class((void *)ehdr->elf32);
          const t_elf_sh		shdr = elf_get_section_header(ehdr, index);

          return (elf_get_section_header_type(&shdr, class));
  }

  t_elf_sh	elf_get_section_header_by_type(const t_elf_h *ehdr, uint32_t type)
  {
          const unsigned char	class = elf_get_elfh_e_ident_class((void *)ehdr->elf32);
          const uint16_t		shnum = elf_get_real_shnum(ehdr, class);
          uint16_t			index;
          t_elf_sh			shdr;

          index = 0;
          while (index < shnum)
          {
                  shdr = elf_get_section_header(ehdr, index++);
                  if (shdr.elf32 && elf_get_section_header_type(&shdr, class) == type)
                          return (shdr);
          }
          shdr.elf32 = NULL;
          return (shdr);
  }

  bool	elf_valid_elf_section_header_handler(unsigned char elf_class, uint64_t *symtab, const t_elf_h *ehdr,
                          uint64_t index)
  {
          const t_elf_sh	shdr = elf_get_section_header(ehdr, index);

          if (!index)
                  return (elf_valid_first_section_header(elf_class, ehdr, &shdr));
          return (elf_valid_section_header(elf_class, &shdr, index, ehdr, symtab));
  }

#+end_src

#+begin_src c :tangle include/format_elf.h :mkdirp yes

  // elf_valid_elf_section_header_2
  bool	elf_valid_section_header(unsigned char elf_class, const t_elf_sh *shdr, uint16_t index, const t_elf_h *ehdr, uint64_t *symtab);
  bool	elf_valid_first_section_header(unsigned char elf_class, const t_elf_h *ehdr,
                          const t_elf_sh *shdr);
  uint32_t	elf_get_section_header_type_by_index(const t_elf_h *ehdr,
                          uint16_t index);
  t_elf_sh	elf_get_section_header_by_type(const t_elf_h *ehdr, uint32_t type);
  bool	elf_valid_elf_section_header_handler(unsigned char elf_class,  uint64_t *symtab, const t_elf_h *ehdr, uint64_t index);

#+end_src


* How do the packer logic: 
1. Add the string "....WOODY....\n" to the string section end. Kind of inecesary would be better for image size, performance, let's cues, don't add info in .rodata this way ~[const] char woody_str[] = {'.','.','.','.','W','O','O','D','Y','.','.','.','.',0}~
   1. Go Section header =.rodata=
      1. Increment =sh_size= as needed.
      2. write the content u want.
         1. *Warning* Null ended.
      3. Test with =readelf -r .rodata= for check is all fine, and that the executable still working with *64b * and *32b*.
2. Add instruction to the program:
   Choice:
   - [ ] Create a new section (Cleaner, less error prune, maybe could be suspect an unusual section)
   - [X] Append at a existing section '.text' (Easier)
   - Go to the Section header ='text'=.
     1. go to the end of the section
        1. =begin_elf_file= (mmap) + =sh_offset= + =original_sh_size=
     2. write the instructions i want.
     3. if =Shdr '.text'= is loadable as should be:
        1. Increment =sh_size= as needed.
           1. *Carefull* alignment.
     4. Get Phdr
        1. Save =Shdr '.text'.sh_offset and original_sh_size=
        2. Search on phdr for one where: p_offset == sh_offset && p_filesz == sh_size the point to the pointer of the file.
     5. Modify =Phdr= and increment =p_filesz= and =p_memz= should be same size as =sh_size=.
     6. Check the set of instructions was added for both arch =objdump -M intel -D | tail=
   - Change entrypoint to execute the new instructions
     1. Detect how to jmp to the original entrypoint:
     2. Write the instructions.
     3. Check the program executed fine for both arch =./program=
3. Compress and Encrypt
   1. Compress and Encrypt n sections
      1. I will choose =.rodata and .text=  maybe variants with prefix =s= just for =data= and  =bss= i don't think that will worth encrypt that sections for global and static var (=initialized= or =not initialized= respectively).
      2. maybe would be better use relocations table for .rodata info ....

    Relocation Table: PE files have a relocation table that specifies which addresses need to be adjusted when the executable is loaded. This is particularly important if the executable is not loaded at its preferred base address.

* How
     implement the relocation logic in your unpacking code. This code will read the relocation table, determine the necessary adjustments, and apply them to the relevant sections of the executable.
       
#+begin_src c :tangle include/format_elf.h :mkdirp yes
 #endif 
#+end_src

