#+title: ELF
#+PROPERTY: header-args:c :tangle "inject_code.c" :mkdirp yes
* Validate ELF

** What makes invalid a elf file:
*** TODO Invalid Elf_header.
:LOGBOOK:
CLOCK: [2025-06-10 Tue 12:27]--[2025-06-10 Tue 13:29] =>  1:02
CLOCK: [2025-06-10 Tue 11:18]--[2025-06-10 Tue 11:49] =>  0:31
:END:
- Invalid Section_header.
- Invalid Program_header.

** Implementation
*** Optimization
When test if invalid elf_header we could check also if is =e_type == ET_EXEC= we should check if is an executable.
*** Abstraction

#+begin_comment
For simplify the 64/32 bits management we're going to use unions and getters for take the values from the unions and abstract the 64/32 for the code.
Abbreviation
Program header = Phdr = _ph       
Section header = Shdr = _sh       
Elf header = ehdr = _h       
#+end_comment

#+begin_src c :tangle format_elf.h :prologue "#ifndef FORMAT_ELF\n# define FORMAT_ELF\n"
  # include <elf.h>    // Typedef ELFNN_*, ST_BIND, ...

  typedef union u_elf_h
  {
    const Elf32_Ehdr	*elf32;
    const Elf64_Ehdr	*elf64;
  }	t_elf_h;

  typedef union u_elf_ph
  {
    const Elf32_Phdr	*elf32;
    const Elf64_Phdr	*elf64;
  }	t_elf_ph;

  typedef union u_elf_sh
  {
    const Elf32_Shdr	*elf32;
    const Elf64_Shdr	*elf64;
  }	t_elf_sh;

  typedef union u_elf_sym
  {
    const Elf32_Sym	*elf32;
    const Elf64_Sym	*elf64;
  }	t_elf_sym;
#+end_src

*** Validation ELF_header
**** How works the header.
search man elf for the attributes of the structure:
=unsigned char e_ident[EI_NIDENT];= {Magicnbr, 32/64b, Dataencoding, version, OSABI, ABI, ...}
=uint16_t      e_type;= object file type {exec, rel, dyn, ...}
=uint16_t      e_machine;= required archictecture for a file *Ignored*
=uint32_t      e_version;= elf file version
=ElfN_Addr     e_entry;= entrypoint of the program (where is the first instruction to execute
=ElfN_Off      e_phoff;= Program header offset
=ElfN_Off      e_shoff;= Section header offset
=uint32_t      e_flags;= Processor-specific flags  *Ignored*
=uint16_t      e_ehsize;= elf header size Bytes
=uint16_t      e_phentsize;= elf program header size Bytes
=uint16_t      e_phnum;= nbr of program header
=uint16_t      e_shentsize;= elf section header size Bytes
=uint16_t      e_shnum;= nbr of section header
=uint16_t      e_shstrndx;= index of section header string (inside the array of section header)
***** Edge Cases
When the num of  =S/Phdr= is more than could be handle by uint16_t (65535) the first Sheader got the real info of =e_shnum, e_phnum, shstrndx=
*What value got then:*
- ===e_shnum == SHN_UNDEF===
  - ==e_shnum = shdr[0].sh_size== //Where to find
- ===e_phnum == PN_XNUM===
  - ==e_phnum = shdr[0].sh_info== //Where to find
- ===e_shstrndx == SHN_XINDEX===
  - ==e_shstrndx = shdr[0].sh_link== //Where to find
**** Coding
***** Creating the getters
I use the union attribute elf32 for e_ident case be a 64 is in the same place the first position (polymorphism).
#+begin_src c :tangle get_eh.c :prologue '#include "format_elf.h"'

  uint16_t	get_elfh_type(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_type);
    return (ehdr->elf64->e_type);
  }

  uint16_t	get_elfh_machine(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_machine);
    return (ehdr->elf64->e_machine);
  }

  uint32_t	get_elfh_version(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_version);
    return (ehdr->elf64->e_version);
  }

  uint32_t	get_elfh_flags(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_flags);
    return (ehdr->elf64->e_flags);
  }

  uint32_t	get_elfh_flags(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_flags);
    return (ehdr->elf64->e_flags);
  }

  uint16_t	get_elfh_shstrndx(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shstrndx);
    return (ehdr->elf64->e_shstrndx);
  }

#+end_src

#+begin_src c :tangle format_elf.h
  //get_eh
  uint16_t		get_elfh_type(const t_elf_h *hdr);
  uint16_t		get_elfh_machine(const t_elf_h *ehdr);
  uint32_t		get_elfh_version(const t_elf_h *ehdr);
  uint32_t		get_elfh_flags(const t_elf_h *ehdr);
  uint16_t		get_elfh_shstrndx(const t_elf_h *ehdr);

#+end_src

#+begin_src c :tangle get_eh_1.c :prologue '#include "format_elf.h"'

  uint16_t	get_elfh_ehsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_ehsize);
    return (ehdr->elf64->e_ehsize);
  }

  uint16_t	get_elfh_phentsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_phentsize);
    return (ehdr->elf64->e_phentsize);
  }

  uint16_t	get_elfh_phnum(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_phnum);
    return (ehdr->elf64->e_phnum);
  }

  uint16_t	get_elfh_shentsize(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shentsize);
    return (ehdr->elf64->e_shentsize);
  }

  uint16_t	get_elfh_shnum(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shnum);
    return (ehdr->elf64->e_shnum);
  }
#+end_src

#+begin_src c :tangle format_elf.h
  //get_eh_1
  uint16_t		get_elfh_ehsize(const t_elf_h *ehdr);
  uint16_t		get_elfh_phentsize(const t_elf_h *ehdr);
  uint16_t		get_elfh_phnum(const t_elf_h *ehdr);
  uint16_t		get_elfh_shentsize(const t_elf_h *ehdr);
  uint16_t		get_elfh_shnum(const t_elf_h *ehdr);
#+end_src

#+begin_src c :tangle get_eh_2.c :prologue '#include "format_elf.h"'
  
uint64_t	get_elfh_entry(const t_elf_h *ehdr)
{
	const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_entry);
	return (ehdr->elf64->e_entry);
}

uint64_t	get_elfh_phoff(const t_elf_h *ehdr)
{
	const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_phoff);
	return (ehdr->elf64->e_phoff);
}

uint64_t	get_elfh_shoff(const t_elf_h *ehdr)
{
	const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return ((uint64_t)ehdr->elf32->e_shoff);
	return (ehdr->elf64->e_shoff);
}

int	get_struct_size_elf_header(char *elf_mmap)
{
	if (elf_mmap[EI_CLASS] == ELFCLASS32)
		return (sizeof (Elf32_Ehdr));
	else if (elf_mmap[EI_CLASS] == ELFCLASS64)
		return (sizeof (Elf64_Ehdr));
	return (0);
}
#+end_src

#+begin_src c :tangle format_elf.h
  // get_eh_2
  uint64_t		get_elfh_entry(const t_elf_h *ehdr);
  uint64_t		get_elfh_phoff(const t_elf_h *ehdr);
  uint64_t		get_elfh_shoff(const t_elf_h *ehdr);
  int				get_struct_size_elf_header(char *elf_mmap);

#+end_src
***** Creating the getters for the edge cases

#+begin_src c :tangle get_real_data.c
  #include "format_elf.h"

  uint16_t	get_real_phnum(const t_elf_eh *ehdr)
  {
    const t_elf_sh	shdr = get_section_header(ehdr, 0);
    uint16_t		phnum;

    phnum = get_elfh_phnum(ehdr);
    if (PN_XNUM == phnum)
      phnum = get_section_header_info(&shdr,
                                      get_elfh_e_ident_class((void *)ehdr->elf32));
    return (phnum);
  }

  uint16_t	get_real_shstrndx(const t_elf_eh *ehdr, unsigned char class)
  {
    const t_elf_sh	shdr = get_section_header(ehdr, 0);
    uint16_t		shstrndx;

    shstrndx = get_elfh_shstrndx(ehdr);
    if (shstrndx == SHN_XINDEX)
      shstrndx = get_section_header_link(&shdr, class);
    return (shstrndx);
  }

  uint16_t	get_real_shnum(const t_elf_eh *ehdr, unsigned char class)
  {
    const t_elf_sh	shdr = get_section_header(ehdr, 0);
    uint16_t		shnum;

    shnum = get_elfh_shnum(ehdr);
    if (shnum == SHN_UNDEF)
      shnum = get_section_header_size(&shdr, class);
    return (shnum);
  }

  uint16_t	get_elfh_shstrndx(const t_elf_h *ehdr)
  {
    const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

    if (class == ELFCLASS32)
      return (ehdr->elf32->e_shstrndx);
    return (ehdr->elf64->e_shstrndx);
  }
#+end_src
****** Prototype of the functions
#+begin_src  c :tangle format_elf.h

  //get_real_data
  uint64_t	get_real_shnum(const t_elf_h *ehdr, unsigned char class);
  uint64_t	get_real_shstrndx(const t_elf_h *ehdr, unsigned char class);
  uint64_t	get_real_phnum(const t_elf_h *ehdr);

#+end_src

***** Create the validation
#+begin_src c :tangle valid_elf_h_attrib.c
  #include "format_elf.h"

  bool	is_valid_elf_shoff(const t_elf_h *ehdr, off_t *elf_size)
  {
    return (get_elfh_shoff(ehdr) < (uint64_t )*elf_size
            && get_elfh_shoff(ehdr)
            >= (uint64_t)get_struct_size_elf_header((char *)ehdr->elf32));
  }

  bool	is_valid_elf_phoff(const t_elf_h *ehdr, off_t *elf_size)
  {
    return (!get_elfh_phnum(ehdr)
            || (get_elfh_phoff(ehdr) >= (uint64_t)get_struct_size_elf_header((char *)ehdr->elf32)
            && get_elfh_phoff(ehdr) < (uint64_t)elf_size));
  }
#+end_src

#+begin_src c :tangle format_elf.h
  // valid_elf_h_attrib
  
  bool	is_valid_elf_shoff(const t_elf_h *ehdr, off_t *elf_size);
  bool	is_valid_elf_phoff(const t_elf_h *ehdr, off_t *elf_size);

#+end_src

#+begin_src c :tangle validate_elf_h.c
  #include "format_elf.h"

  bool is_file_size_enought_for_elf_header(off_t file_size, void *elf_mmap)
  {
    if (file_size < EI_NIDENT)
      return (false);
    return (file_size
            >= get_struct_size_elf_header(elf_mmap));
  }

  bool	is_valid_elf_data_format(char *elf_mmap)
  {
    const char	data = elf_mmap[EI_DATA];

    return (ELFDATA2LSB == data|| ELFDATA2MSB == data);
  }

  bool	is_valid_elf_version(char *elf_mmap)
  {
    return (EV_CURRENT == elf_mmap[EI_VERSION]);
  }

  bool	is_executable_elf_file(const t_elf_h *ehdr, off_t *file_size)
  {
    return (ET_EXEC == get_elfh_type(ehdr));
  }
#+end_src

#+begin_src c :tangle format_elf.h
  // validate_elf_h
  bool is_file_size_enought_for_elf_header(off_t file_size, void *elf_mmap)
  bool	is_valid_elf_data_format(char *elf_mmap)
  bool	is_a_valid_elf_version(char *elf_mmap)
  bool	is_an_executable_elf_file(const t_elf_h *ehdr, off_t *file_size)

#+end_src

#+begin_src c :tangle validate_elf_h_1.c :prologue "#include "format_elf.h"
  bool	elf_valid_section_size(const t_elf_h *ehdr)
  {
    return (get_elfh_shentsize(ehdr) == get_section_header_struct_size(ehdr));
  }

  bool	elf_valid_section_header_string_index(const t_elf_h *ehdr)
  {
    const uint16_t	shnum = get_elfh_shnum(ehdr);

    return (shnum && shnum > get_elfh_shstrndx(ehdr));
  }

  bool	elf_valid_elfh_class(const char *e_indent)
  {
    const unsigned char	class = get_elfh_e_ident_class((void *)e_indent);

    return (class == ELFCLASS64 || class == ELFCLASS32);
  }

  bool	elf_valid_ident(off_t file_size, void *elf_mmap)
  {
    return (is_file_size_enought_for_elf_header(file_size, elf_mmap)
            && valid_elf_magic_number(elf_mmap)
            && valid_elfh_class(elf_mmap) && valid_data(elf_mmap)
            && valid_version(elf_mmap));
  }

#+end_src

#+begin_src c :tangle format_elf.h
  // valid_elf_h_1
  bool	elf_valid_section_size(const t_elf_h *ehdr);
  bool	elf_valid_ident(off_t file_size, void *elf_mmap);
  bool	elf_valid_elfh_class(const char *e_indent);
  bool	elf_valid_section_header_string_index(const t_elf_h *ehdr);
  bool	elf_valid_section_size(const t_elf_h *ehdr)

#+end_src

#+begin_src c :tangle valid_elf_h_2 :prologue '#include "format_elf.h"'
  bool	valid_t_elf_h(const t_elf_h *ehdr)
  {
    return (elf_valid_section_size(ehdr)
            && elf_valid_section_header_string_index(ehdr)
            && is_valid_elf_shoff(ehdr)
            && is_valid_elf_phoff(ehdr));
  }

  bool	valid_elf_header(const t_elf_h *ehdr, file_size)
  {
    return (valid_ident(file_size, ehdr) && valid_t_elf_h(ehdr));
  }
#+end_src

#+begin_src c :tangle format_elf.h
  // valid_t_elf_h_2
  bool	valid_elf_header(const t_elf_h *ehdr, file_size);
  bool	valid_t_elf_h(const t_elf_h *ehdr);

#+end_src

*** TODO Validation ELF_Sections.
change =t_bag=  struct to =size= and =class= add things as needed.

**** Getters Section Headers
#+begin_src c :tangle  get_elfsh_data.c :prologue '#include "format_elf.h"'

uint64_t	get_section_header_struct_size(const t_elf_h *ehdr)
{
	const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return (sizeof (Elf32_Shdr));
	else if (class == ELFCLASS64)
		return (sizeof (Elf64_Shdr));
	ft_printf("Exit Failure section header size\n");
	exit(EXIT_FAILURE);
}

bool	is_special_section_index(uint16_t index)
{
	static const uint16_t	special_section_index[] = {SHN_COMMON, SHN_ABS,
		SHN_XINDEX};
	int						i;

	if (SHN_LOPROC <= index && index >= SHN_HIOS)
		return (true);
	i = 0;
	while (i < SPECIAL_SECTION_INDEX_SIZE && index != special_section_index[i])
		i++;
	return (i != SPECIAL_SECTION_INDEX_SIZE);
}

t_elf_sh	get_section_header(const t_elf_h *ehdr, uint16_t index)
{
	const uint64_t			sh_offset = get_elfh_shoff(ehdr);
	const uint64_t			sh_size = get_section_header_struct_size(ehdr);
	const void				*base = (void*)ehdr->elf32;
	t_elf_sh				shdr;

	if (!sh_offset || index >= get_elfh_shnum(ehdr)
		|| is_special_section_index(index))
	{
		shdr.elf32 = NULL;
		return (shdr);
	}
	shdr.elf64 = base + sh_offset + index * sh_size;
	return (shdr);
}

uint64_t	get_section_header_offset(const t_elf_sh *shdr, unsigned char class)
{
	if (!shdr->elf32)
	{
		ft_printf("section header Invalid\n");
		return (0);
	}
	if (class == ELFCLASS32)
		return ((uint64_t)shdr->elf32->sh_offset);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_offset);
	ft_printf("Exit Failure section header offset\n");
	exit(EXIT_FAILURE);
}

bool	valid_null_end_string_table(const t_elf_sh *shstrtab,
			unsigned char class, char *ptr)
{
	const uint64_t	size = get_section_header_size(shstrtab, class);

	if (!ptr || !size)
		return (false);
	return (!ptr[size - 1]);
}

#+end_src

#+begin_src c :tangle get_elfsh_data_1.c :prologue '#include "format_elf.h"'
uint32_t	get_section_header_type(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_type);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_type);
	ft_printf("Exit Failure section header type\n");
	exit(EXIT_FAILURE);
}

uint32_t	get_section_header_flags(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_flags);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_flags);
	ft_printf("Exit Failure section header flags\n");
	exit(EXIT_FAILURE);
}

uint64_t	get_section_header_size(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_size);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_size);
	ft_printf("Exit Failure section header size\n");
	exit(EXIT_FAILURE);
}

uint32_t	get_section_header_link(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_link);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_link);
	ft_printf("Exit Failure section header link\n");
	exit(EXIT_FAILURE);
}

uint32_t	get_section_header_info(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_info);
	else if (class == ELFCLASS64)
		return (shdr->elf64->sh_info);
	ft_printf("Exit Failure section header info\n");
	exit(EXIT_FAILURE);
}
#+end_src

#+begin_src c :tangle get_elfsh_data_2.c :prologue '#include "format_elf.h"'

uint64_t	get_section_header_addralign(const t_elf_sh *shdr,
		unsigned char class)
{
	if (class == ELFCLASS32)
		return ((uint64_t)shdr->elf32->sh_addralign);
	return (shdr->elf64->sh_addralign);
}

uint32_t	get_section_header_entsize(const t_elf_sh *shdr,
			unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_entsize);
	return (shdr->elf64->sh_entsize);
}

uint32_t	get_section_header_addr(const t_elf_sh *shdr, unsigned char class)
{
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_addr);
	return (shdr->elf64->sh_addr);
}
#+end_src

#+begin_src c :tangle get_elfsh_data_3.c :prologue '#include "format_elf.h"'

const char	*get_section_string_table(const t_elf_h *ehdr)
{
	const uint16_t	sh_str_index = get_elfh_shstrndx(ehdr);
	const t_elf_sh	shstrtab_shdr = get_section_header(ehdr, sh_str_index);
	const uint64_t	shstr_tab_offset = get_section_header_offset(&shstrtab_shdr,
			get_elfh_e_ident_class(ehdr->elf32->e_ident));
	char			*ptr;

	if (!shstr_tab_offset && !shstrtab_shdr.elf32)
		return (NULL);
	ptr = (char *)ehdr->elf32 + shstr_tab_offset;
	if (!valid_null_end_string_table(&shstrtab_shdr,
			get_elfh_e_ident_class((void *)ehdr->elf32), ptr))
		return (NULL);
	return (ptr);
}

uint32_t	get_section_header_name(const t_elf_sh *shdr, unsigned char class)
{
	if (!shdr || !shdr->elf32)
		return (0);
	if (class == ELFCLASS32)
		return (shdr->elf32->sh_name);
	if (class == ELFCLASS64)
		return (shdr->elf32->sh_name);
	ft_printf("Exit Failure section header name\n");
	exit(EXIT_FAILURE);
}

const char	*get_section_name(const char *str_tab, uint16_t index_str_tab)
{
	if (!str_tab)
		return (NULL);
	return (str_tab + index_str_tab);
}

uint16_t	get_elfh_shstrndx(const t_elf_h *ehdr)
{
	const unsigned char	class = get_elfh_e_ident_class(ehdr->elf32->e_ident);

	if (class == ELFCLASS32)
		return (ehdr->elf32->e_shstrndx);
	else if (class == ELFCLASS64)
		return (ehdr->elf64->e_shstrndx);
	exit(EXIT_FAILURE);
}
#+end_src

**** Validation Functions

#+begin_src c :tangle valid_section_header.c :prologue '#include "format_elf.h"'

bool	valid_elf_section_header_symtab_shndx(t_bag *bag, const t_elf_h *ehdr)
{
	const t_elf_sh	shdr = get_section_header_by_type(ehdr, SHT_SYMTAB_SHNDX);

	if (!shdr.elf32)
		return (false);
	return (get_section_header_link(&shdr, bag->elf_class)
		== bag->symtab_index);
}

bool	valid_elf_section_headers(t_bag *bag, const t_elf_h *ehdr)
{
	const uint16_t	eh_shnum = get_real_shnum(ehdr, bag->elf_class);
	uint16_t		id;

	bag->real_shstrndx = get_real_shstrndx(ehdr, bag->elf_class);
	if (!eh_shnum && bag->real_shstrndx)
		return (false);
	id = 0;
	while (id < eh_shnum && valid_elf_section_header(bag, ehdr, id))
		id++;
	if (id < eh_shnum)
		return (false);
	if (bag->real_shstrndx >= eh_shnum
		|| get_section_header_type_by_index(ehdr, bag->real_shstrndx)
		!= SHT_STRTAB)
		return (false);
	return (!bag->symtab_shndx
		|| valid_elf_section_header_symtab_shndx(bag, ehdr));
}
#+end_src

#+begin_src c :tangle valid_elf_section_header_2.c :prologue '#include "format_elf.h"'

bool	valid_elf_section_header_symtab_shndx(t_bag *bag, const t_elf_h *ehdr)
{
	const t_elf_sh	shdr = get_section_header_by_type(ehdr, SHT_SYMTAB_SHNDX);

	if (!shdr.elf32)
		return (false);
	return (get_section_header_link(&shdr, bag->elf_class)
		== bag->symtab_index);
}

bool	valid_elf_section_headers(t_bag *bag, const t_elf_h *ehdr)
{
	const uint16_t	eh_shnum = get_real_shnum(ehdr, bag->elf_class);
	uint16_t		id;

	bag->real_shstrndx = get_real_shstrndx(ehdr, bag->elf_class);
	if (!eh_shnum && bag->real_shstrndx)
		return (false);
	id = 0;
	while (id < eh_shnum && valid_elf_section_header(bag, ehdr, id))
		id++;
	if (id < eh_shnum)
		return (false);
	if (bag->real_shstrndx >= eh_shnum
		|| get_section_header_type_by_index(ehdr, bag->real_shstrndx)
		!= SHT_STRTAB)
		return (false);
	return (!bag->symtab_shndx
		|| valid_elf_section_header_symtab_shndx(bag, ehdr));
}

#+end_src
*** Validation ELF_Programs.

* How do the packer logic: 
1. Add the string "....WOODY....\n" to the string section end for more easy.

   1. Go Section header =.rodata=
      1. Increment =sh_size= as needed.
      2. write the content u want.
         1. *Warning* Null ended.
      3. Test with =readelf -r .rodata= for check is al fine, and that the executable still working with *64b * and *32b*.
  
2. Add instruction to the program:
   Choice:
   - [ ] Create a new section (Cleaner, less error prune, maybe could be suspect an unusual section)
   - [X] Append at a existing section '.text' (Easier)


   1. Go to the Section header ='text'=.
      1. go to the end of the section

         1. =begin_elf_file= (mmap) + =sh_offset= + =original_sh_size=

      2. write the instructions i want.

      3. if =Shdr '.text'= is loadable as should be:

         1. Increment =sh_size= as needed.

            1. *Carefull* alignment.

      4. Get Phdr

         1. Save =Shdr '.text'.sh_offset and original_sh_size=

         2. Search on phdr for one where: p_offset == sh_offset && p_filesz == sh_size
      5. Modify =Phdr= and increment =p_filesz= and =p_memz= should be same size as =sh_size=.
      6. Check the set of instructions was added for both arch =objdump -D | tail=
         
3. Change entrypoint to execute the new instructions
    1. Detect how to jmp to the original entrypoint:

    2. Write the instructions.

    3. Check the program executed fine for both arch =./program=

       
