#+title: inject_code_elf
#+PROPERTY: header-args:c :tangle "srcs/inject_code_elf.c" :mkdirp yes
#+PROPERTY: header-args:asm :mkdirp yes

*  WalkThrought
Modify makefile to compile the differents targets and start testing with it.
1. [X ]copy the hole file and get execution perm.
   1. [X] Test that execute normally.
2. [-] Add the function || code to execute at the end of the =.text= section.
   1. [X] Get the assembly code to insert in the file.
   2. [-] update sh and ph sh_size and p_filesz p_mems,
      1. [ ] In case the target file got different endianess that our machine we should swap the offset .... previous and later to update the data correctly.
      2. [-] update Shdr  // check for get the info and go modified ehdr, phdr.
         1. [X] sh_size
         2. [ ] sh_offset I should change the elfh e_shoff When the payload need to increment the alignament_size.
         3. [X] fill with 0x0 to reach align.      2. [ ] update Ehdr
         4. [ ] I should change the e_entrypoint to the payload.
         5. [ ] I case payload increment over alignment size we must modify sh_offset.
      3. [ ] Program header
         1. [ ] p_memsz, p_filesz
         2. [ ] Validation  p_align         ~Values  of  zero  and one mean no alignment is required.  Other‐ wise, p_align should be a positive, integral power of  two,  and
              p_vaddr should equal p_offset, modulo p_align.~

   3. [ ] check the code appear. ~objdump -M intel -D | tail~
   4. [ ] In case a function add the symbol. // less cues if not function just inject the code.
      1. [ ] In case append to a current function should update the current size of the symbol ...
   5. [ ] move the entrypoint to your code.
   6. [ ] Test that work.
   7. [ ] from your code jmp to the OG address to execute.
3. [ ] Start making the encrypt (rot13 for testing purpose)
   1. [ ] Force to maps region of memory in to new places
   2. [ ] Will see soon
   
     

#+begin_src c :tangle srcs/elf/POC/add_instructions.c :mkdirp yes
  // TODO May create a struct file with mmap and size ?
  #include "format_elf.h"
  #include <string.h>
  #include <stdbool.h>
  #include <unistd.h>
  #include <stdio.h>
  #include <stdint.h>
  #include <fcntl.h>
  #include <sys/mman.h>
  #include <stdlib.h> //Malloc


  uint64_t get_alignment_size(uint64_t alignment, uint64_t size)
  {
    return (((size + alignment - 1) / alignment) * alignment);
  }

  // Maybe paranoia
  bool is_little_endian_the_cpu(void)
  {
    uint32_t num = 1;

    return (*(uint8_t *)&num == 1);
  }

  // Maybe paranoia
  uint64_t swap_endianess(uint64_t value)
  {
    uint64_t swapped;
    uint64_t i;

    swapped = 0;
    i = 0;
    while (i < 8)
      {
        swapped |= ((value >> (i * 8)) & 0xFF) << ((7 - i) * 8);
        i++;
      }
    return swapped;
  }

  //setters Warning no use the mmap pointer will modify the og file or couldn't write cause no write perm.
  // segfault for advice if i am doing something bad.
  void elf_shdr_set_addr(t_elf_sh *shdr, uint64_t value, unsigned char class)
  {
    if (class == ELFCLASS32) 
      {
        printf("elf32\n");
        shdr->elf32->sh_addr = (uint32_t) value;
      }
    else
      {
        printf("elf64\n");
        shdr->elf64->sh_addr = value;
      }
  }

  //setters Warning no use the mmap pointer will modify the og file or couldn't write cause no write perm
  // segfault for advice if i am doing something bad.
  void elf_shdr_set_size(t_elf_sh *shdr, uint64_t value, unsigned char class)
  {
    if (class == ELFCLASS32) 
      {
        printf("elf32\n");
        shdr->elf32->sh_size = (uint32_t) value;
      }
    else
      {
        printf("elf64\n");
        shdr->elf64->sh_size = value;
      }
  }

  int main(int argc, char **argv)
  {
    //Validation params
    if (argc != 2)
      {
        printf("usage: %s [filename]\n", *argv);
        return (1);
      }  	
    //Open File
    int fd = open(argv[1], O_RDONLY); 
    if (fd < 0)
      return (2);
    // Get size file
    const off_t file_size = lseek(fd, 0, SEEK_END);
    if ((off_t) -1 == file_size || (off_t) -1 == lseek(fd, 0, SEEK_SET))
      {
        close(fd);
        return (3);
      }
    // Save on memory all the file
    void *elf_mmap = mmap(NULL, file_size, PROT_READ, MAP_SHARED, fd, 0);
    close(fd);
    if (!elf_mmap)
      return (1);
    // open the file where we gonna add the payload
    int packed = open("woody", O_CREAT | O_TRUNC | O_RDWR, S_IRWXU | S_IRWXG | S_IRWXO);
    if (packed < 0)
      {
        munmap(elf_mmap, file_size);
        return (4);
      } // not main part POC starting
    // Get the section to include the payload
    t_elf_sh		shdr;
    char 			*name_str;
    const t_elf_h 	ehdr = (t_elf_h){.elf32 = elf_mmap};
    const uint64_t 	shnum = elf_get_elfh_shnum(&ehdr);
    const char	 	*sh_str_tab = elf_get_section_string_table(&ehdr);
    const unsigned char 	class = elf_get_elfh_e_ident_class(elf_mmap);
    uint64_t 		i;

    i = 0;
    while (i < shnum) //run for each section_header
      {
        shdr = elf_get_section_header(&ehdr, i);
        name_str = (char *)elf_get_section_name(sh_str_tab, elf_get_section_header_name(&shdr, class));
        if (!strcmp(name_str, ".text"))
          break ;
        i++;
      }
    // In case find the section show relevant info function.
    if (shnum <= i)
      return (5);
    //Payload info
    char payload[] = {'\x48', '\x31', '\xff'};
    const size_t payload_size = sizeof(payload) / sizeof(*payload);
    //Section header math.
    uint64_t sh_addralign = elf_get_section_header_addralign(&shdr, class);
    const uint64_t sh_size = elf_get_section_header_size(&shdr, class);
    uint64_t sh_offset = elf_get_section_header_offset(&shdr, class);
    uint64_t old_align_size = get_alignment_size(sh_addralign, sh_size);
    uint64_t new_align_size = get_alignment_size(sh_addralign, sh_size + payload_size);
    uint64_t sh_offset_payload = sh_offset + sh_size;
    uint64_t sh_elf_offset = (void *)shdr.elf32 - (void *)ehdr.elf32;
    uint64_t writed;
    // Insert payload.
    //2. [ ] I should change the elfh e_shoff in case that increment the alignment.

    // Create copy to modify further
    uint64_t shdr_struct_size = elf_get_section_header_struct_size (&ehdr);
    t_elf_sh shdr_cp = (t_elf_sh){.elf32 = malloc(shdr_struct_size)};
    if (!shdr_cp.elf32)
      {
        close (packed);
        return (5);
      }
    memcpy(shdr_cp.elf32, shdr.elf32, shdr_struct_size); 

    writed = 0;
    if (old_align_size != new_align_size) // <
      {
        /* uint64_t unused_space = old_align_size - sh_size; */
        uint64_t payload_unused_space = new_align_size - (sh_size + payload_size);
        printf("Need to push the next offset at least on Shdr\n");
        writed += write(packed, elf_mmap, sh_offset_payload);

        // Insert payload.
        writed += write(packed, payload, payload_size);
        while (payload_unused_space--) //Write alignment
          writed += write(packed, "\0", 1);
        payload_unused_space = new_align_size - (sh_size + payload_size); //Reset the value
        writed += write(packed, elf_mmap + (writed - payload_size), sh_elf_offset - (writed - payload_size)); // Need to keep thinking.
      }
    else
      {

        if (sh_elf_offset > sh_offset_payload)
          {
            printf("Copy the file content until write payload i miss modify the offset -> %lu\n", sh_offset_payload);
            writed += write(packed, elf_mmap + writed, sh_offset_payload - writed);
            printf ("write elf og until payload offset. writed -> %lu\n", writed);
            writed += write(packed, payload, payload_size);
            printf ("write payload_size. writed ->  %lu\n", writed);
            printf ("Cause i use the same elf alignment i don't need to fill the new. pointer move writed bytes %p need advance offset to '.data' section header. writed ->  %lu. sh_elf_offset -> %lu\n" , elf_mmap, writed, sh_elf_offset);
            writed += write(packed, elf_mmap + writed, sh_elf_offset - writed);
            printf("Go to the section header '.text' %lu\n", writed);
            elf_shdr_set_size(&shdr_cp, sh_size + payload_size, class);//setter sh_size.
            writed += write(packed, shdr_cp.elf32, shdr_struct_size);
            printf("write shdr '.text' %lu\n", writed);
            writed += write(packed, elf_mmap + writed, file_size - writed);
            printf("write the rest of the elf file.\n");
          }
        else // At least for Object files.
          {
            printf("Copy the file content until section '.text' sh_elf_offset -> %lu\n", sh_elf_offset);
            writed += write(packed, elf_mmap + writed, sh_elf_offset - writed);
            elf_shdr_set_size(&shdr_cp, sh_size + payload_size, class);
            printf("Write the modify shdr: writed -> %lu\n", writed);
            writed += write(packed, shdr_cp.elf32, shdr_struct_size);
            _printf("Writed the modify shdr: writed -> %lu\n", writed);
            printf ("write elf og until payload offset. writed -> %lu\n", writed);
            writed += write(packed, elf_mmap + writed, sh_offset_payload - writed);
            printf ("writed elf og until payload offset. writed -> %lu\n", writed);
            writed += write(packed, payload, payload_size);
            printf ("writed payload. writed -> %lu\n", writed);
            printf ("write payload_size ->  %lu\n", payload_size);
            printf("write the rest of the file '.text' %lu\n", writed);
            writed += write(packed, elf_mmap + writed, file_size - writed);
            printf("write the rest of the elf file.\n");
          }

      }
    free(shdr_cp.elf32);
    munmap(elf_mmap, file_size);
    close(packed);
    return (0);
  }
#+end_src

#+begin_src c :tangle no
  include/format_elf.h

    //add_instructions



#+end_src

* Try to make more indepedience the code not that hardcoded.

* make the jump to the entrypoint.
#+begin_src c :tangle no
  void create_jump_payload(uint64_t entry_point, char *payload) {
    // Assuming payload has enough space
    // Clear the payload
    memset(payload, 0, 64); // Adjust size as needed

    // Create a jump instruction
    // For a near jump, we use the opcode 0xE9
    payload[0] = 0xE9; // Opcode for JMP

    // Calculate the relative address
    // The address of the instruction following the jump
    uint64_t next_instruction_address = (uint64_t)(payload + 5); // 5 bytes for the jump instruction

    // Calculate the relative offset
    int32_t offset = (int32_t)(entry_point - next_instruction_address);

    // Copy the offset into the payload (little-endian)
    memcpy(payload + 1, &offset, sizeof(offset));
}
#+end_src
