#+title: inject_code_elf
#+PROPERTY: header-args:c :tangle "srcs/inject_code_elf.c" :mkdirp yes
#+PROPERTY: header-args:asm :mkdirp yes

*  WalkThrought
Modify makefile to compile the differents targets and start testing with it.
1. [X ]copy the hole file and get execution perm.
   1. [X] Test that execute normally.
2. [-] Add the function || code to execute at the end of the =.text= section.
   1. [X] Get the assembly code to insert in the file.
   2. [ ] update sh and ph sh_size and p_filesz p_mems,
      1. [ ] Section in case size and align left free space in case increment, increment the rest of headers with greater offset and fill with 0x0 to reach align.
      2. [ ] Programe header
      3. [ ] Symbol tab modify 
   3. [ ] check the code appear. ~objdump -M intel -D | tail~
   4. [ ] In case a function add the symbol. // less cues if not function just inject the code.
      1. [ ] In case append to a current function should update the current size of the symbol ...
   5. [ ] move the entrypoint to your code.
   6. [ ] Test that work.
   7. [ ] from your code jmp to the OG address to execute.
3. [ ] Start making the encrypt (rot13 for testing purpose)
   1. [ ] Force to maps region of memory in to new places
   2. [ ] Will see soon
    
 
     

#+begin_src c :tangle srcs/elf/POC/add_instructions.c :mkdirp yes
      //0:	48 31 ff             	xor    rdi,rdi 3 B increment
      // char payload[] = {x48, x31, xff};
      // const size_t size_payload = sizeof(payload) / sizeof(*payload);
      // TODO May create a struct file with mmap and size ?
      // TODO May create a struct elf Ehdr, Shdr, Phdr, SYMTAB.
    #include "format_elf.h"
    #include <string.h>
    #include <stdbool.h>
    #include <unistd.h>
    #include <stdio.h>
    #include <stdint.h>
    #include <fcntl.h>
    #include <sys/mman.h>

  int main(int argc, char **argv)
    {
      if (argc != 2)
        {
          printf("usage: %s [filename]\n", *argv);
          return (1);
        }  	
      int fd = open(argv[1], O_RDONLY); 
      if (fd < 0)
          return (1);
      off_t file_size = lseek(fd, 0, SEEK_END);
      if ((off_t) -1 == file_size || (off_t) -1 == lseek(fd, 0, SEEK_SET))
        {
          close(fd);
          return (1);
        }
      void *elf_mmap = mmap(NULL, file_size, PROT_READ, MAP_SHARED, fd, 0);
      close(fd);
      if (!elf_mmap)
        return (1);
      char payload[] = {'\x48', '\x31', '\xff'};
      const size_t size_payload = sizeof(payload) / sizeof(*payload);
      int packet = open("woody", O_CREAT | O_TRUNC, S_IRWXU | S_IRWXG | S_IRWXO);
      if (packet < 0)
        {
          munmap(elf_mmap, file_size);
          return (1);
        }
      t_elf_h ehdr = (t_elf_h){.elf32 = elf_mmap};
      uint64_t shoff = elf_get_elfh_shoff(&ehdr);
      uint64_t shnum = elf_get_elfh_shnum(&ehdr);
      uint64_t phoff = elf_get_elfh_phoff(&ehdr);
      uint64_t phnum = elf_get_elfh_phnum(&ehdr);
      t_elf_sh	shdr = elf_get_section_header(&ehdr, 0);
      t_elf_ph	phdr = elf_get_program_header(&ehdr, 0);
      const char *sh_str_tab = elf_get_section_string_table(&ehdr);
      const unsigned char class = elf_get_elfh_e_ident_class(elf_mmap);
      uint64_t i = 0;
      while (i < shnum)
        {
          shdr = elf_get_section_header(&ehdr, i);
          const uint64_t name_ndx = elf_get_section_header_name(&shdr, class);
          printf("index: %lu -> name_ndx: %lu -> name: %s -> sh_offset: %lu\n", i, name_ndx, elf_get_section_name(sh_str_tab, name_ndx), elf_get_section_header_offset(&shdr, class));
          i++;
        }
      munmap(elf_mmap, file_size);
      close(packet);
      return (0);
    }
#+end_src

#+begin_src c :tangle no
  include/format_elf.h

    //add_instructions
#+end_src
